const UI_TEXT = {
  it: {
    nav: {
      dashboard: 'Dashboard',
      techrelease: 'Tech Release',
      about: 'About',
      admin: 'Admin',
      openMenu: 'Apri menu',
      closeMenu: 'Chiudi menu',
      mainNavigation: 'Navigazione principale',
      lightTheme: 'Tema chiaro',
      darkTheme: 'Tema scuro',
      switchToLight: 'Passa a tema chiaro',
      switchToDark: 'Passa a tema scuro',
      language: 'Lingua',
      user: 'Utente',
      logout: 'Logout',
      infra: 'Infrastructure Insights',
      githubrepo: 'GitHub Repo',
    },
    common: {
      loading: 'Caricamento dati in corso...',
      unavailable: 'non disponibile',
      close: 'Chiudi',
      yes: 'si',
      no: 'no',
      online: 'Online',
      offline: 'Offline',
    },
    auth: {
      welcome: 'Benvenuto',
      subtitle: 'Accedi con le tue credenziali',
      email: 'Email',
      password: 'Password',
      remove: 'Rimuovi',
      invalidCredentials: 'Credenziali non valide',
      authError: 'Errore autenticazione - riprova più tardi',
      loading: 'Accesso in corso...',
      login: 'Accedi',
    },
    dashboard: {
      releaseTitle: 'latest tech release',
      downloadsTitle: 'download',
      cveTitle: 'CVE',
      newsTitle: 'news',
      latestNews: 'ultime news Proxmox',
      newsSource: 'Feed prodotti',
      newsCommunity: 'Google News',
      newsLoading: 'Caricamento news...',
      newsError: 'Impossibile caricare le news.',
      newsModalTitle: 'News',
      readNews: 'Leggi',
      latestCve: 'ultime CVE',
      product: 'Prodotto',
      severity: 'Severity',
      score: 'Score',
      date: 'Data',
      link: 'Link',
      all: 'Tutte',
      noCve: 'Nessuna CVE trovata.',
      cveError: 'Dati CVE non disponibili. Riprova tra qualche minuto.',
      cveLoading: 'Caricamento CVE in corso…',
      cveComingSoon: 'Prossimamente — dati CVE Linux in arrivo.',
      sevCritical: 'Critical',
      sevHigh: 'High',
      sevMedium: 'Medium',
      sevLow: 'Low',
      releaseLoadError: 'Impossibile caricare le release Proxmox.',
      downloadsLoadError: 'Impossibile caricare i download Proxmox.',
      noReleasePve9: 'Nessuna release trovata per Proxmox VE 9.',
      noReleasePve8: 'Nessuna release trovata per Proxmox VE 8.',
      noReleasePbs: 'Nessuna release trovata per Proxmox Backup Server.',
      noReleasePdm: 'Nessuna release trovata per Proxmox Datacenter Manager.',
      latestRelease: 'ultima release',
      releaseName: 'Nome Release',
      version: 'Versione',
      codename: 'Codename',
      releaseDate: 'Data Rilascio',
      eos: 'End Of Support',
      fileSize: 'Dimensione file',
      lastUpdated: 'Ultimo aggiornamento',
      download: 'Download',
      installer: 'Installer',
      noDownloadPve: 'Nessun download trovato per Proxmox Virtual Environment.',
      noDownloadPbs: 'Nessun download trovato per Proxmox Backup Server.',
      noDownloadPdm: 'Nessun download trovato per Proxmox Datacenter Manager.',
      noDownloads: 'Nessun download disponibile.',
    },
    releases: {
      title: 'tech release',
      allVersions: 'Tutte le versioni',
      allBranches: 'Tutti i rami',
      filter: 'Filtro...',
      releaseName: 'Nome Release',
      version: 'Versione',
      codename: 'Codename',
      releaseDate: 'Data Rilascio',
      eos: 'End Of Support',
      buildNumber: 'Build #',
      type: 'Tipo',
    },
    admin: {
      title: 'Pannello admin',
      deniedTitle: 'Admin',
      deniedMessage: 'Accesso riservato a vlt@hub.local.',
      saveChanges: 'Salva modifiche',
      usersTab: 'Utenti',
      sistemaTab: 'Sistema',
      users: 'Utenti',
      newUser: 'Nuovo utente',
      email: 'Email',
      name: 'Nome',
      role: 'Ruolo',
      password: 'Password',
      newPassword: 'Nuova password',
      keepPassword: 'lascia vuoto per mantenere',
      addUser: 'Aggiungi utente',
      remove: 'Rimuovi',
      githubActions: 'GitHub Actions',
      dispatchToken: 'Token dispatch',
      dispatchTokenPlaceholder: 'Incolla qui il token (github_pat_...)',
      totalUsers: 'Utenti totali',
      adminCount: 'Amministratori',
      userCount: 'Utenti standard',
      appInfo: 'Info applicazione',
      appVersion: 'Versione',
      appBuild: 'Build',
      appUpdated: 'Aggiornato',
      settingsFile: 'File settings',
      deployRepo: 'Repository',
      deployBranch: 'Branch deploy',
      comingSoon: 'Prossimamente',
      viewVisibility: 'Visibilità viste',
      viewsNote: 'Le viste disabilitate sono in manutenzione: nascoste agli utenti, visibili all\'admin con badge.',
      viewNames: { dashboard: 'Dashboard', techrelease: 'Tech Release', about: 'About', infra: 'Insights', githubrepo: 'GitHub Repo' },
      infraSettings: 'Impostazioni Insights',
      infraNote: 'Abilita o disabilita i singoli provider dell\'Insights. Un provider disabilitato non comparirà nella vista.',
      maintenance: 'Manutenzione',
      clearFilter: 'tutti',
      loadOkDev: 'Sorgente auth locale caricata da public/settings.enc.json.',
      loadOkProd: 'Sorgente auth caricata dal deploy.',
      loadError: 'Impossibile caricare gli utenti auth.',
      missingNewUser: 'Nuovo utente e password sono obbligatori.',
      duplicateUser: 'Utente gia presente.',
      userAdded: 'Utente aggiunto alla lista locale.',
      emptyList: 'Lista utenti vuota',
      duplicateList: 'Sono presenti username duplicati',
      adminRequired: "L'utente admin vlt@hub.local deve essere presente",
      missingPassword: 'Password mancante per',
      tokenRequired: 'Token GitHub richiesto per avviare GitHub Actions da produzione.',
      dispatchError: 'GitHub Actions non avviata',
      dispatchOk: 'GitHub Actions avviata. Il nuovo deploy genererà settings.enc.json.',
      fileOk: 'Nuovo settings.enc.json generato. In dev salvalo o sostituiscilo in public/.',
      saveError: 'Salvataggio auth fallito.',
      noteDispatch: 'Le password non escono in chiaro: viene generato un payload AES-GCM con hash PBKDF2. Salva modifiche avvia direttamente GitHub Actions.',
      noteDev: 'Le password non escono in chiaro: in dev viene generato settings.enc.json locale. Se il browser lo consente, scegli public/settings.enc.json dal file picker.',
    },
    about: {
      description: 'Hub centrale per tecnici e sysadmin che gestiscono infrastrutture',
      descriptionSuffix: '',
      builtWith: 'Realizzato con',
      legalTitle: 'Note legali e disclaimer',
      licenseTitle: 'Licenza',
      licenseMeta: 'Proprietaria — vlT',
      closeLabel: 'Chiudi',
      rights: 'Tutti i diritti riservati',
      info: {
        version: 'Versione',
        build: 'Build',
        updated: 'Aggiornato',
        initialBuild: 'Build iniziale',
        license: 'Licenza',
        licenseValue: 'Proprietaria',
        platform: 'Piattaforma',
      },
      licenseText: `nex tech hub — Licenza Proprietaria

Copyright © 2026 Veronesi Lorenzo (vlT). Tutti i diritti riservati.

nex tech hub è un portale proprietario. L'accesso e l'utilizzo sono riservati
esclusivamente ai soggetti espressamente autorizzati dall'autore.

Senza preventiva autorizzazione scritta dell'autore, sono espressamente vietati:

· Accesso non autorizzato — l'utilizzo del portale è consentito esclusivamente
  a chi riceve esplicita autorizzazione dall'autore
· Modifica — adattamento, traduzione o creazione di opere derivate
· Redistribuzione — copia, fork, ripubblicazione, sublicenza o repackaging;
  la distribuzione in qualsiasi forma, sorgente o compilata, è riservata esclusivamente all'autore
· Reverse engineering — decompilazione o disassemblaggio dell'output minificato o compilato
· Sfruttamento commerciale — vendita o integrazione in prodotti o servizi commerciali

Tutti i diritti di proprietà intellettuale, inclusi copyright, segreti commerciali e know-how,
rimangono esclusivamente in capo a Veronesi Lorenzo (vlT). La presente licenza non trasferisce alcun diritto di proprietà.
Il software è fornito "così com'è", senza garanzie di alcun tipo.

La licenza è disciplinata dalla legge italiana. Foro competente esclusivo: Milano (MI).
Per richieste di accesso o autorizzazioni: veronesilorenzo@outlook.com`,
      legal: [
        "Tutti i marchi, nomi commerciali, loghi e segni distintivi citati in questa applicazione restano di proprietà esclusiva dei rispettivi titolari. Il loro utilizzo ha finalità esclusivamente descrittive, informative o di riferimento e non implica approvazione, partnership o affiliazione.",
        "nex tech hub è un'applicazione indipendente, non affiliata, approvata o sponsorizzata da società o organizzazioni i cui marchi possono comparire nei contenuti.",
        "I riferimenti a prodotti, servizi, tecnologie o materiali di terze parti sono inclusi esclusivamente per finalità di interoperabilità, descrizione tecnica o informazione.",
        "Questo software non è affiliato né sponsorizzato da Proxmox Server Solutions GmbH. \"Proxmox\" è un marchio registrato dei rispettivi titolari.",
        "nex tech hub è fornito \"così com'è\" e \"secondo disponibilità\", senza garanzie di alcun tipo. L'utilizzo avviene a rischio esclusivo dell'utente.",
        "L'autore non è responsabile per eventuali danni derivanti dall'uso o dall'impossibilità di utilizzare l'applicazione, anche qualora fosse stato informato della possibilità di tali danni.",
        "L'eventuale trattamento di dati personali avviene nel rispetto della normativa applicabile in materia di protezione dei dati, incluso il GDPR e la relativa normativa nazionale.",
        "L'autore si riserva il diritto di modificare il presente disclaimer in qualsiasi momento pubblicando la versione aggiornata nell'app o nel repository ufficiale. L'uso continuato dopo le modifiche costituisce accettazione.",
        "Salvo ove espressamente indicato, il codice sorgente, la struttura, i contenuti originali, la grafica, il layout e il design di nex tech hub sono tutelati dalla normativa sulla proprietà intellettuale e restano riservati all'autore. La pubblicazione del codice su repository pubblici o privati non concede, di per sé, alcuna licenza, autorizzazione al riutilizzo o trasferimento di diritti.",
      ],
    },
    infrastructure: {
      title: 'infrastructure view',
      uploadTitle: 'upload pmxtools',
      processing: 'Elaborazione report pmxtools in corso...',
      dropActive: 'Rilascia qui il file JSON di pmxtools',
      dropIdle: 'Trascina qui il file JSON di pmxtools o clicca per selezionarlo',
      missingCli: 'Non hai pmxtools-cli? Scaricalo.',
      missingUi: 'Non hai pmxtools? Scaricalo.',
      releaseLoading: 'Recupero ultima release...',
      latestRelease: 'Ultima release',
      cliNotice: "Strumento CLI per la raccolta dati dall'API Proxmox VE. Genera il report JSON da caricare qui sopra.",
      cliNoticeStrong: 'Richiede accesso API al nodo Proxmox.',
      releaseError: 'Errore nel recupero release',
      uiTitle: 'pmxtools',
      uiDescription: "Applicazione desktop di reportistica per Proxmox VE: dashboard avanzata, export completo dell'infrastruttura, visualizzazione nodi, VM, LXC, storage e rete in un'unica interfaccia nativa.",
      uiDescriptionStrong: 'Si collega direttamente alle API di Proxmox VE',
      uiDescriptionSuffix: 'non richiede pmxtools-cli.',
      invalidReportTitle: 'Report pmxtools non valido',
      invalidFormat: 'Formato pmxtools non valido',
      invalidJson: 'File JSON non valido',
      readError: 'Errore durante la lettura del file',
      close: 'Chiudi',
      noTechAvailable: 'Nessuna tecnologia abilitata. Contatta l\'admin per abilitare Proxmox o VMware.',
      vmwUploadTitle: 'upload vmwtools',
      vmwProcessing: 'Elaborazione file JSON in corso...',
      vmwDropActive: 'Rilascia qui il file JSON',
      vmwDropIdle: 'Trascina qui il file JSON o clicca per selezionarlo',
      vmwInvalidTitle: 'vmwtools non valido',
      vmwInvalidReportVmwtools: "Il file caricato non è un report vmwtools valido: campo 'vmwtools' mancante o non valido",
      vmwInvalidReportSection: "Il file caricato non è un report vmwtools valido: sezione 'report' mancante o non valida",
      vmwInvalidReportCapturedAt: "Il file caricato non è un report vmwtools valido: campo 'report.captured_at' mancante o non valido",
      vmwInvalidReportName: "Il file caricato non è un report vmwtools valido: campo 'report.name' mancante o non valido",
      convertedReportInvalid: 'Report convertito non valido',
      convertedReportAvailable: 'report vmwtools disponibile',
      useConvertedReport: 'usa il report appena convertito',
      loadReport: 'carica report',
      rvtoolsDivider: 'oppure converti da RVTools',
      rvtoolsSubtitle: 'converte un report RVTools XLSX in formato vmwtools JSON',
      rvtoolsProcessing: 'Conversione file XLSX in corso...',
      rvtoolsDropActive: 'Rilascia qui il file XLSX di RVTools',
      rvtoolsDropIdle: 'Trascina qui il file XLSX di RVTools da convertire o clicca per selezionarlo',
      rvtoolsMissing: 'Non hai software RVTools? scaricalo!',
      rvtoolsCompleted: 'conversione completata',
      downloadJson: 'scarica JSON',
      reset: 'reset',
      rvtoolsInvalidTitle: 'File XLSX non valido',
      rvtoolsInvalidConversion: 'Conversione vmwtools non valida',
      rvtoolsConvertError: 'File XLSX non valido o conversione fallita',
      rvtoolsOnlyXlsx: 'Puoi caricare solo un file .xlsx valido',
    },
    infraDashboard: {
      tabs: {
        datacenter: 'Datacenter',
        vm: 'VM',
        lxc: 'LXC',
        nodes: 'Nodi',
        storage: 'Storage',
        network: 'Network & SDN',
        margins: 'Margini infra',
        cluster: 'Cluster',
        vmSummaryTab: 'Riepilogo VM',
        licenses: 'Licenze',
        esxiNodes: 'Nodi ESXi',
        resourcePools: 'Resource Pool',
        vmList: 'VM List',
        datastore: 'Datastore',
        networkVmware: 'Network Port Groups',
      },
      loadAnother: 'Carica altro report pmxtools',
      loadAnotherVmware: 'Carica altro report vmwtools',
      reportCaptured: 'report catturato',
      generalInfo: 'Informazioni generali',
      datacenterType: 'Tipo datacenter',
      primaryNode: 'Nodo principale',
      pveVersion: 'Versione PVE',
      release: 'Release',
      totalNodes: 'Nodi totali',
      totalEsxiNodes: 'Nodi ESXi totali',
      totalVms: 'VM totali',
      totalLxcs: 'LXC totali',
      totalStorages: 'Storage totali',
      totalNetworks: 'Network totali',
      resourceSummary: 'Riepilogo risorse datacenter',
      clusterSummary: 'Riepilogo cluster',
      clusterName: 'Nome cluster',
      configuredNodes: 'Nodi configurati',
      quorum: 'Quorum',
      present: 'Presente',
      absent: 'Assente',
      onlineNodes: 'Nodi online',
      localNode: 'Nodo locale',
      id: 'ID',
      ip: 'IP',
      status: 'Stato',
      role: 'Ruolo',
      local: 'Locale',
      remote: 'Remoto',
      running: 'Running',
      stopped: 'Stopped',
      template: 'Template',
      totalVcpu: 'vCPU totali',
      totalRam: 'RAM totale',
      totalDisk: 'Disco totale',
      totalStorage: 'Storage totale',
      vmSummary: 'Riepilogo VM',
      windowsVmActiveSummary: 'Riepilogo VM Windows (attive)',
      linuxVmActiveSummary: 'Riepilogo VM Linux (attive)',
      otherVmActiveSummary: 'Riepilogo VM AltroOS (attive)',
      otherVms: 'VM altro',
      licenseSummary: 'Riepilogo licenze vSphere',
      license: 'Licenza',
      key: 'Chiave',
      expiration: 'Scadenza',
      esxiNodesView: 'Nodi ESXi',
      model: 'Modello',
      vmOnNode: 'VM sul nodo',
      filterResourcePool: 'Filtra Resource Pool...',
      vmCount: 'Conteggio VM',
      exportXls: 'esporta xls',
      primaryStorage: 'Storage primario',
      snapshotDetails: 'Dettagli snapshot',
      notPresent: 'Non presenti',
      noSnapshot: 'Nessuna snapshot',
      lxcSummary: 'Riepilogo LXC',
      vmView: 'Vista VM',
      lxcView: 'Vista LXC',
      nodesView: 'Vista nodi',
      storageTitle: 'Storage',
      networkBridge: 'Network bridge',
      zones: 'SDN - Zone',
      vnets: 'SDN - VNets',
      subnet: 'SDN - Subnet',
      noConfig: 'Nessuna configurazione',
      filterVm: 'Filtra VM...',
      filterLxc: 'Filtra LXC...',
      filterNodes: 'Filtra nodi...',
      filterStorage: 'Filtra storage...',
      filterNetwork: 'Filtra network...',
      filterZones: 'Filtra zone...',
      filterVnets: 'Filtra VNets...',
      filterSubnet: 'Filtra subnet...',
      name: 'Nome',
      node: 'Nodo',
      nodeFallback: 'Nodo',
      primaryDisk: 'Disco primario',
      primaryNetwork: 'Rete primaria',
      notes: 'Note',
      version: 'Versione',
      uptime: 'Uptime',
      socket: 'Socket',
      core: 'Core',
      thread: 'Thread',
      clock: 'Clock',
      management: 'Management',
      type: 'Tipo',
      shared: 'Condiviso',
      total: 'Totale',
      used: 'Usato',
      free: 'Libero',
      ports: 'Porte',
      address: 'Indirizzo',
      gateway: 'Gateway',
      vlanAware: 'VLAN aware',
      alias: 'Alias',
      zone: 'Zone',
      tag: 'Tag',
      bridge: 'Bridge',
      ipam: 'IPAM',
      snat: 'SNAT',
      marginTitle: 'Utilizzato datacenter con margine',
      marginSelect: 'Seleziona un margine per adattare i valori',
      totalShort: 'TOT',
      inUse: 'in uso',
    },
  },
  en: {
    nav: {
      dashboard: 'Dashboard',
      techrelease: 'Tech Release',
      about: 'About',
      admin: 'Admin',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      mainNavigation: 'Main navigation',
      lightTheme: 'Light theme',
      darkTheme: 'Dark theme',
      switchToLight: 'Switch to light theme',
      switchToDark: 'Switch to dark theme',
      language: 'Language',
      user: 'User',
      logout: 'Logout',
      infra: 'Infrastructure Insights',
      githubrepo: 'GitHub Repo',
    },
    common: {
      loading: 'Loading data...',
      unavailable: 'unavailable',
      close: 'Close',
      yes: 'yes',
      no: 'no',
      online: 'Online',
      offline: 'Offline',
    },
    auth: {
      welcome: 'Welcome',
      subtitle: 'Sign in with your credentials',
      email: 'Email',
      password: 'Password',
      remove: 'Remove',
      invalidCredentials: 'Invalid credentials',
      authError: 'Authentication error - try again later',
      loading: 'Signing in...',
      login: 'Sign in',
    },
    dashboard: {
      releaseTitle: 'latest tech release',
      downloadsTitle: 'downloads',
      cveTitle: 'CVE',
      newsTitle: 'news',
      latestNews: 'latest Proxmox news',
      newsSource: 'Product feed',
      newsCommunity: 'Google News',
      newsLoading: 'Loading news...',
      newsError: 'Unable to load news.',
      newsModalTitle: 'News',
      readNews: 'Read',
      latestCve: 'latest CVE',
      product: 'Product',
      severity: 'Severity',
      score: 'Score',
      date: 'Date',
      link: 'Link',
      all: 'All',
      noCve: 'No CVEs found.',
      cveError: 'CVE data unavailable. Please try again in a few minutes.',
      cveLoading: 'Loading CVEs…',
      cveComingSoon: 'Coming soon — Linux CVE data in progress.',
      sevCritical: 'Critical',
      sevHigh: 'High',
      sevMedium: 'Medium',
      sevLow: 'Low',
      releaseLoadError: 'Unable to load Proxmox releases.',
      downloadsLoadError: 'Unable to load Proxmox downloads.',
      noReleasePve9: 'No release found for Proxmox VE 9.',
      noReleasePve8: 'No release found for Proxmox VE 8.',
      noReleasePbs: 'No release found for Proxmox Backup Server.',
      noReleasePdm: 'No release found for Proxmox Datacenter Manager.',
      latestRelease: 'latest release',
      releaseName: 'Release Name',
      version: 'Version',
      codename: 'Codename',
      releaseDate: 'Release Date',
      eos: 'End Of Support',
      fileSize: 'File Size',
      lastUpdated: 'Last Updated',
      download: 'Download',
      installer: 'Installer',
      noDownloadPve: 'No download found for Proxmox Virtual Environment.',
      noDownloadPbs: 'No download found for Proxmox Backup Server.',
      noDownloadPdm: 'No download found for Proxmox Datacenter Manager.',
      noDownloads: 'No downloads available.',
    },
    releases: {
      title: 'tech release',
      allVersions: 'All versions',
      allBranches: 'All branches',
      filter: 'Filter...',
      releaseName: 'Release Name',
      version: 'Version',
      codename: 'Codename',
      releaseDate: 'Release Date',
      eos: 'End Of Support',
      buildNumber: 'Build #',
      type: 'Type',
    },
    admin: {
      title: 'Admin panel',
      deniedTitle: 'Admin',
      deniedMessage: 'Access restricted to vlt@hub.local.',
      saveChanges: 'Save changes',
      usersTab: 'Users',
      sistemaTab: 'System',
      users: 'Users',
      newUser: 'New user',
      email: 'Email',
      name: 'Name',
      role: 'Role',
      password: 'Password',
      newPassword: 'New password',
      keepPassword: 'leave empty to keep',
      addUser: 'Add user',
      remove: 'Remove',
      githubActions: 'GitHub Actions',
      dispatchToken: 'Dispatch token',
      dispatchTokenPlaceholder: 'Paste your token here (github_pat_...)',
      totalUsers: 'Total users',
      adminCount: 'Administrators',
      userCount: 'Standard users',
      appInfo: 'App info',
      appVersion: 'Version',
      appBuild: 'Build',
      appUpdated: 'Updated',
      settingsFile: 'Settings file',
      deployRepo: 'Repository',
      deployBranch: 'Deploy branch',
      comingSoon: 'Coming soon',
      viewVisibility: 'View visibility',
      viewsNote: 'Disabled views are under maintenance: hidden from users, visible to admin with a badge.',
      viewNames: { dashboard: 'Dashboard', techrelease: 'Tech Release', about: 'About', infra: 'Insights', githubrepo: 'GitHub Repo' },
      infraSettings: 'Insights Settings',
      infraNote: 'Enable or disable individual Insights providers. A disabled provider will not appear in the view.',
      maintenance: 'Maintenance',
      clearFilter: 'all',
      loadOkDev: 'Local auth source loaded from public/settings.enc.json.',
      loadOkProd: 'Auth source loaded from deploy.',
      loadError: 'Unable to load auth users.',
      missingNewUser: 'New user and password are required.',
      duplicateUser: 'User already exists.',
      userAdded: 'User added to the local list.',
      emptyList: 'User list is empty',
      duplicateList: 'Duplicate usernames found',
      adminRequired: 'Admin user vlt@hub.local must be present',
      missingPassword: 'Missing password for',
      tokenRequired: 'GitHub token required to start GitHub Actions in production.',
      dispatchError: 'GitHub Actions not started',
      dispatchOk: 'GitHub Actions started. The new deploy will generate settings.enc.json.',
      fileOk: 'New settings.enc.json generated. In dev, save it or replace it in public/.',
      saveError: 'Auth save failed.',
      noteDispatch: 'Passwords never leave in plaintext: an AES-GCM payload with PBKDF2 hashes is generated. Save changes starts GitHub Actions directly.',
      noteDev: 'Passwords never leave in plaintext: dev generates a local settings.enc.json. If the browser allows it, choose public/settings.enc.json from the file picker.',
    },
    about: {
      description: 'Central hub for technicians and sysadmins managing',
      descriptionSuffix: 'infrastructure',
      builtWith: 'Built with',
      legalTitle: 'Legal notices & disclaimer',
      licenseTitle: 'License',
      licenseMeta: 'Proprietary — vlT',
      closeLabel: 'Close',
      rights: 'All rights reserved',
      info: {
        version: 'Version',
        build: 'Build',
        updated: 'Updated',
        initialBuild: 'Initial build',
        license: 'License',
        licenseValue: 'Proprietary',
        platform: 'Platform',
      },
      licenseText: `nex tech hub — Proprietary License

Copyright © 2026 Veronesi Lorenzo (vlT). All rights reserved.

nex tech hub is a proprietary portal. Access and use are reserved exclusively
to individuals expressly authorized by the author.

Without prior written authorization from the author, the following are expressly prohibited:

· Unauthorized access — use of the portal is permitted only to those
  who receive explicit authorization from the author
· Modification — adaptation, translation, or creation of derivative works
· Redistribution — copying, forking, re-publishing, sub-licensing, or repackaging;
  distribution in any form (source or built) is reserved exclusively to the author
· Reverse engineering — decompilation or disassembly of minified/bundled output
· Commercial exploitation — sale, incorporation into commercial products or services

All intellectual property rights (copyright, trade secrets, know-how) remain
exclusively with Veronesi Lorenzo (vlT). This license transfers no ownership rights.
The software is provided "as is", without warranties of any kind.

Governed by Italian law. Exclusive jurisdiction: Milan (MI).
For access requests or licensing inquiries: veronesilorenzo@outlook.com`,
      legal: [
        "All trademarks, trade names, logos and distinctive signs mentioned in this application remain the exclusive property of their respective owners. Their use is solely for descriptive, informational or reference purposes and does not imply any approval, partnership or affiliation.",
        "nex tech hub is an independent application not affiliated with, endorsed or sponsored by any company or organization whose trademarks may appear in the content.",
        "References to third-party products, services, technologies or materials are included solely for interoperability, technical description or informational purposes.",
        "This software is not affiliated with or sponsored by Proxmox Server Solutions GmbH. \"Proxmox\" is a registered trademark of its respective owners.",
        "nex tech hub is provided \"as is\" and \"as available\", without warranties of any kind. Use is at the user's own risk.",
        "The author is not liable for any damages arising from the use or inability to use this application, even if advised of the possibility of such damages.",
        "Personal data processing, if any, occurs in compliance with applicable data protection law including GDPR and national implementation law.",
        "The author reserves the right to modify this disclaimer at any time by publishing the updated version in the app or on the official repository. Continued use after modifications constitutes acceptance.",
        "Except where expressly stated, the source code, structure, original content, graphics, layout and design of nex tech hub are protected by intellectual property law and remain reserved to the author. Publication of code on public or private repositories does not, by itself, grant any license, permission to reuse, or transfer of rights.",
      ],
    },
    infrastructure: {
      title: 'infrastructure view',
      uploadTitle: 'pmxtools upload',
      processing: 'Processing pmxtools report...',
      dropActive: 'Drop the pmxtools JSON file here',
      dropIdle: 'Drag the pmxtools JSON file here or click to select it',
      missingCli: 'Need pmxtools-cli? Download it.',
      missingUi: 'Need pmxtools? Download it.',
      releaseLoading: 'Retrieving latest release...',
      latestRelease: 'Latest release',
      cliNotice: 'CLI tool for collecting data from the Proxmox VE API. It generates the JSON report to upload above.',
      cliNoticeStrong: 'Requires API access to the Proxmox node.',
      releaseError: 'Release retrieval error',
      uiTitle: 'pmxtools',
      uiDescription: 'Standalone desktop reporting application for Proxmox VE: advanced dashboard, complete infrastructure export, node, VM, LXC, storage and network views in one native interface.',
      uiDescriptionStrong: 'Connects directly to the Proxmox VE API',
      uiDescriptionSuffix: 'no pmxtools-cli required.',
      invalidReportTitle: 'Invalid pmxtools report',
      invalidFormat: 'Invalid pmxtools format',
      invalidJson: 'Invalid JSON file',
      readError: 'Error while reading the file',
      close: 'Close',
      noTechAvailable: 'No technology enabled. Contact the admin to enable Proxmox or VMware.',
      vmwUploadTitle: 'vmwtools upload',
      vmwProcessing: 'Processing JSON file...',
      vmwDropActive: 'Drop the JSON file here',
      vmwDropIdle: 'Drag the JSON file here or click to select it',
      vmwInvalidTitle: 'Invalid vmwtools report',
      vmwInvalidReportVmwtools: "The uploaded file is not a valid vmwtools report: missing or invalid 'vmwtools' field",
      vmwInvalidReportSection: "The uploaded file is not a valid vmwtools report: missing or invalid 'report' section",
      vmwInvalidReportCapturedAt: "The uploaded file is not a valid vmwtools report: missing or invalid 'report.captured_at' field",
      vmwInvalidReportName: "The uploaded file is not a valid vmwtools report: missing or invalid 'report.name' field",
      convertedReportInvalid: 'Invalid converted report',
      convertedReportAvailable: 'vmwtools report available',
      useConvertedReport: 'use the report just converted',
      loadReport: 'load report',
      rvtoolsDivider: 'or convert from RVTools',
      rvtoolsSubtitle: 'converts an RVTools XLSX report to vmwtools JSON format',
      rvtoolsProcessing: 'Converting XLSX file...',
      rvtoolsDropActive: 'Drop the RVTools XLSX file here',
      rvtoolsDropIdle: 'Drag the RVTools XLSX file here to convert it or click to select it',
      rvtoolsMissing: 'Need RVTools software? Download it!',
      rvtoolsCompleted: 'conversion completed',
      downloadJson: 'download JSON',
      reset: 'reset',
      rvtoolsInvalidTitle: 'Invalid XLSX file',
      rvtoolsInvalidConversion: 'Invalid vmwtools conversion',
      rvtoolsConvertError: 'Invalid XLSX file or conversion failed',
      rvtoolsOnlyXlsx: 'You can upload only one valid .xlsx file',
    },
    infraDashboard: {
      tabs: {
        datacenter: 'Datacenter',
        vm: 'VM',
        lxc: 'LXC',
        nodes: 'Nodes',
        storage: 'Storage',
        network: 'Network & SDN',
        margins: 'Infrastructure margins',
        cluster: 'Cluster',
        vmSummaryTab: 'VM summary',
        licenses: 'Licenses',
        esxiNodes: 'ESXi nodes',
        resourcePools: 'Resource Pool',
        vmList: 'VM List',
        datastore: 'Datastore',
        networkVmware: 'Network Port Groups',
      },
      loadAnother: 'Load another pmxtools report',
      loadAnotherVmware: 'Load another vmwtools report',
      reportCaptured: 'captured report',
      generalInfo: 'General information',
      datacenterType: 'Datacenter type',
      primaryNode: 'Primary node',
      pveVersion: 'PVE version',
      release: 'Release',
      totalNodes: 'Total nodes',
      totalEsxiNodes: 'Total ESXi nodes',
      totalVms: 'Total VMs',
      totalLxcs: 'Total LXC',
      totalStorages: 'Total storage',
      totalNetworks: 'Total networks',
      resourceSummary: 'Datacenter resource summary',
      clusterSummary: 'Cluster summary',
      clusterName: 'Cluster name',
      configuredNodes: 'Configured nodes',
      quorum: 'Quorum',
      present: 'Present',
      absent: 'Absent',
      onlineNodes: 'Online nodes',
      localNode: 'Local node',
      id: 'ID',
      ip: 'IP',
      status: 'Status',
      role: 'Role',
      local: 'Local',
      remote: 'Remote',
      running: 'Running',
      stopped: 'Stopped',
      template: 'Template',
      totalVcpu: 'Total vCPU',
      totalRam: 'Total RAM',
      totalDisk: 'Total disk',
      totalStorage: 'Total storage',
      vmSummary: 'VM summary',
      windowsVmActiveSummary: 'Windows VM summary (active)',
      linuxVmActiveSummary: 'Linux VM summary (active)',
      otherVmActiveSummary: 'Other OS VM summary (active)',
      otherVms: 'Other VMs',
      licenseSummary: 'vSphere license summary',
      license: 'License',
      key: 'Key',
      expiration: 'Expiration',
      esxiNodesView: 'ESXi nodes view',
      model: 'Model',
      vmOnNode: 'VMs on node',
      filterResourcePool: 'Filter Resource Pool...',
      vmCount: 'VM count',
      exportXls: 'export xls',
      primaryStorage: 'Primary storage',
      snapshotDetails: 'Snapshot details',
      notPresent: 'Not present',
      noSnapshot: 'No snapshot',
      lxcSummary: 'LXC summary',
      vmView: 'VM view',
      lxcView: 'LXC view',
      nodesView: 'Nodes view',
      storageTitle: 'Storage',
      networkBridge: 'Network bridge',
      zones: 'SDN - Zones',
      vnets: 'SDN - VNets',
      subnet: 'SDN - Subnet',
      noConfig: 'No configuration',
      filterVm: 'Filter VMs...',
      filterLxc: 'Filter LXC...',
      filterNodes: 'Filter nodes...',
      filterStorage: 'Filter storage...',
      filterNetwork: 'Filter network...',
      filterZones: 'Filter zones...',
      filterVnets: 'Filter VNets...',
      filterSubnet: 'Filter subnet...',
      name: 'Name',
      node: 'Node',
      nodeFallback: 'Node',
      primaryDisk: 'Primary disk',
      primaryNetwork: 'Primary network',
      notes: 'Notes',
      version: 'Version',
      uptime: 'Uptime',
      socket: 'Socket',
      core: 'Core',
      thread: 'Thread',
      clock: 'Clock',
      management: 'Management',
      type: 'Type',
      shared: 'Shared',
      total: 'Total',
      used: 'Used',
      free: 'Free',
      ports: 'Ports',
      address: 'Address',
      gateway: 'Gateway',
      vlanAware: 'VLAN aware',
      alias: 'Alias',
      zone: 'Zone',
      tag: 'Tag',
      bridge: 'Bridge',
      ipam: 'IPAM',
      snat: 'SNAT',
      marginTitle: 'Used datacenter with margin',
      marginSelect: 'Select a margin to adapt the values',
      totalShort: 'TOT',
      inUse: 'in use',
    },
  },
};

export function getUiText(language = 'it') {
  return UI_TEXT[language] || UI_TEXT.it;
}
